# Exercise: Level 2
print(3 + 4) 
print(4 - 3)
print(4 * 3)
print(4 % 3)
print(3 / 4)
print(3 ** 4)
print(3 // 4)

print('José pablo')
print('Irene , olaf , loki')
print('I am from Mexico')
print('I am enjoying 30 days python')

print(type(10))
print(type(9.8))
print(type(3.14))
print(type['Asabeneh','Python','Finland'])
print(type('Jose Pablo'))
print(type('Irene, olaf, loki'))
print(type('I am from Mexico '))